### ISSUE TITLE
You missed an amazon paremter.

### ISSUE THREAD

**Issue by seiterseiter** [KevinRoebert/ClearUrls#1]
ref=

It would be good if we could add our own parameters :)

**Comment by KevinRoebert** [comment]
> It would be good if we could add our own parameters :)

Hi, we work on this feature.

> ref=

The **ref=** parameter is necessary for the amazon login-button. We look for a workaround.

**Comment by KevinRoebert** [comment]
We have found a solution to this problem. But we need to remove the ref = rules from the data.json, until the next update for the addon is passed the check, otherwise the addon crash the Amazon login page.
