### ISSUE TITLE
add ability to see which rules were triggered

### ISSUE THREAD

**Issue by jawz101** [KevinRoebert/ClearUrls#10]
It would be nice to see a detail in the notification of what rule was triggered and what the original url's were and what they are now.

Like on hover or simply log results to console.  Something informative would be nice.

if I could see what the rules did I could understand the concept and offer additional elements to strip out

**Comment by jawz101** [comment]
if I could see what the rules did I could understand the concept and offer additional elements to strip out

**Comment by KevinRoebert** [comment]
We are already working on this feature. Please have a little patience, we have to finish this feature and submit it for review by mozilla. This can take a little time.

**Comment by jawz101** [comment]
Sorry.  Thanks!
