### ISSUE TITLE
ClearUrls makes Firefox 58.0b3 crash on Ubuntu 17.04

### ISSUE THREAD

**Issue by Valeryan24** [KevinRoebert/ClearUrls#12]
Hi, I use ClearUrls 1.1.2.4 (thanks for your work) and Firefox Beta on Ubuntu Zesty 17.04 with the official Mozilla ppa :

https://launchpad.net/~mozillateam/+archive/ubuntu/firefox-next

Up to Firefox 57, all worked well, but since this morning update and version 58.0b3, ClearUrls makes Firefox always crash, either at startup, either just when loaded and click on "New Tab", or "Addons".

FF Window becomes grey, unresponsive and has to be stopped. It happens also even if ClearUrls is the only addon activated.

Please tell me if I can provide useful crash logs :
https://crash-stats.mozilla.com/report/index/45ab8ad3-2a99-4b12-ab6b-367650171115

**Comment by KevinRoebert** [comment]
Hi, we're not able to reproduce this error on Ubuntu Zesty 17.04 VM. We’re hear from similar problems with the new firefox beta, with and without addons. Please update your firefox to a newer version and tell us, if the problem still exists.
