### ISSUE TITLE
ClearURLs freezes Firefox 58 Beta on Windows 10 on Reddit.com if RES extension is always installed.

### ISSUE THREAD

**Issue by smartfonreddit** [KevinRoebert/ClearUrls#13]
I have RES extension and ClearURLs. The browser updates from FIrefox 57 Beta to Firefox 58 Beta. All websites work except for www.reddit.com, visiting which will  freeze the whole browser and make it use 22% CPU and 30% GPU. If I disable RES extension and restart the browser, ClearURLs works properly on Reddit. If I disable ClearURLs, the RES works properly. They just don't get along with one another.

Few days ago I noticed that while opening Reddit RES Dashboard, which loads lots of subreddits in one window, the ClearURLs would detect 8,000 entries and filter few hundred of them. Not sure if it's related.

**Comment by KevinRoebert** [comment]
Hi, we're not able to reproduce this error on Ubuntu Zesty 17.04 VM. We’re hear from similar problems with the new firefox beta, with and without addons. Please update your firefox to a newer version and tell us, if the problem still exists.

See #12.
