### ISSUE TITLE
Opens a blank tab when clicking outside links on Reddit.

### ISSUE THREAD

**Issue by Stealth3** [KevinRoebert/ClearUrls#14]
If I click a link to another site on Reddit it just opens a blank website (about:blank in the url bar). It works though if I right click on the link and open it.

**Comment by KevinRoebert** [comment]
Hi, can you give an example url?

**Comment by Stealth3** [comment]
https://www.reddit.com/r/thewalkingdead/

or go to any subreddit.

Find a link to an outside site (Maggie Grace joins Fear The Walking Dead Season 4)

I click it and it just opens about:blank.

**Comment by grahamperrin** [comment]
## Environment

Waterfox 56.0 on FreeBSD-CURRENT

```text
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% date ; uname -v
Fri  8 Dec 2017 03:00:59 GMT
FreeBSD 12.0-CURRENT #0 r320869: Mon Jul 10 13:57:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% pkg info waterfox | grep -i version
Version        : 56.0.s20171203
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% 
```

## Steps to produce an empty page – _not_ `about:blank`

1. https://www.reddit.com/r/firefox/comments/7cqeng/webassembly_support_now_shipping_in_all_major/ 
2. <kbd>Control</kbd>-Click the linked phrase, _WebAssembly support now shipping in all major browsers_

### Expected

- https://blog.mozilla.org/blog/2017/11/13/webassembly-in-browsers/ in a new tab

### Actual result

- <https://out.reddit.com/t3_7cqeng?url=https%3A%2F%2Fblog.mozilla.org%2Fblog%2F2017%2F11%2F13%2Fwebassembly-in-browsers%2F&token=AQAA5w0qWhTy3kNQXbE5OU-UjpcVdgtwVr1uyH_l0ddLiBzf3PGV&app_name=reddit.com> in a new tab, as an empty page **without** progress to the expected URL

### Workaround

- switch off the _Filters_ feature of ClearURLs 1.1.2.5
- reload the referring (Reddit) page, repeat steps (1) and (2).

**Comment by KevinRoebert** [comment]
Does it help?

**Comment by Stealth3** [comment]
Does what help? There was no update to the add-on.

**Comment by KevinRoebert** [comment]
> Does what help? There was no update to the add-on.

This was the update...

>  KevinRoebert closed this in 4025f6b 7 hours ago

**Comment by Thorin-Oakenpants** [comment]
FYI: using @grahamperrin steps to reproduce & ClearURLs 1.1.2.5
- went to https://www.reddit.com/r/firefox/comments/7cqeng/webassembly_support_now_shipping_in_all_major/
- clicked on title
- I get the page ( https://blog.mozilla.org/blog/2017/11/13/webassembly-in-browsers/ ) in the **SAME* tab

With ClearURLs disabled, I get the same behavior. So the fix seems to be working - thanks

**Comment by Stealth3** [comment]
It's working correctly now for me it seems! I tried turning off the filters before and turning them back on (to manually update them? not sure if that works) and it didn't fix anything. I tried it again and restarted the browser and now Reddit links seem to be working as intended. I'm glad graham could explain my issue in great depth and thank you Kevin for fixing it!

**Comment by KevinRoebert** [comment]
ClearURLs load the new rule file only on browser start :)
