### ISSUE TITLE
ClearURLs 1.1.2.5 and Google Hangouts frame /webchat/frame3

### ISSUE THREAD

**Issue by grahamperrin** [KevinRoebert/ClearUrls#17]
At https://hangouts.google.com/ the frame --

`https://hangouts.google.com/webchat/frame3`

-- will not load with ClearURLs _Filters_ enabled. 

## Screen recording

[2017-12-09 08:22.ogv.zip](https://github.com/KevinRoebert/ClearUrls/files/1544802/2017-12-09.08.22.ogv.zip)

A frame from that recording: 

![2017-12-09 08 23 33 frame](https://user-images.githubusercontent.com/192271/33797246-73276c86-dcfc-11e7-80cb-08f66f49d8b5.png)

Available on request: two more screen recordings (a little earlier, a little longer). 

## Environment

Waterfox 56.0 on FreeBSD-CURRENT.

**Comment by KevinRoebert** [comment]
We will investigate.

**Comment by KevinRoebert** [comment]
I've found the error. Hangouts need the field `zx` on the subdomains `hangouts.google.com` and `*.client-channel.google.com`. I'm not on PC, so I will fix it tomorrow.

**Comment by KevinRoebert** [comment]
I hope it works :)

**Comment by KevinRoebert** [comment]
Can anybody confirm the fix?

**Comment by Atavic** [comment]
No GOOG here, let's ask https://github.com/grahamperrin

**Comment by Atavic** [comment]
No GOOG here, let's ask @grahamperrin

**Comment by grahamperrin** [comment]
@Atavic what was the question, did it relate to this issue?

**Comment by Atavic** [comment]
Yes, the [*fix*](https://github.com/KevinRoebert/ClearUrls/commit/6fe3af326d2b2660533d02fdea8d96189d670e0f) should be tested.

**Comment by grahamperrin** [comment]
Fix confirmed, thanks ☑️
