### ISSUE TITLE
ClearURLs: explain that not all enhancements/fixes result in a change of version

### ISSUE THREAD

**Issue by grahamperrin** [KevinRoebert/ClearUrls#18]
At <https://github.com/KevinRoebert/ClearUrls/issues/14#issuecomment-350453351> a few hours ago: 

> ClearURLs load the new rule file only on browser start :)

The descriptive text at https://addons.mozilla.org/addon/clearurls/ might benefit from a short paragraph to explain that behaviour. 

Previously, I imagined that each improvement to ClearURLs would result in a version change; an update from `addons.mozilla.org`. My confusion at <https://github.com/KevinRoebert/ClearUrls/issues/8#issuecomment-340207575>, for example. 

Thanks!

**Comment by grahamperrin** [comment]
## Rule-&Hash-Status

Until a few minutes ago, the _Rule-&Hash-Status_ area was mysterious to me. 

I never thought to click in/around that area: 

- because the text below the line is greyed out (not obviously a link); and 
- because I wanted to never accidentally click on the _Reset counter_ button.

**Comment by KevinRoebert** [comment]
Thanks for your questions. I will write some wiki articles into this GitHub Repo.

> Until a few minutes ago, the Rule-&Hash-Status area was mysterious to me.
This is a new feature that was request in #9. We want to inform the user about a change of the rules. To check if the rules are correct downloaded, we check the hash value of the rule-file. So, 3 different states are possible:

1. "**unchanged**": Nothing happens, the rules are up to date
2. "**authorized, changed**": ClearURLs has downloaded new rules and everything is fine
3. "**unauthorized, changed**": ClearURLs has downloaded new rules, but something goes wrong, so ClearURLs is using the old rules and tries to download the new rules by the next browser start

**Comment by grahamperrin** [comment]
Thanks, 

> "**authorized, changed**": ClearURLs has downloaded new rules and everything is fine

… and a restart of the browser will allow the new rules to become effective (yes?)

**Comment by KevinRoebert** [comment]
> Thanks,
> 
> >"authorized, changed": ClearURLs has downloaded new rules and everything is fine

> … and a restart of the browser will allow the new rules to become effective (yes?)

As soon as this message is displayed, the new rules are effective. ClearURLs download on browser start the new rule file, if everything ok, ClearURLs displays "**authorized, changed**", if something was changed or "**unchanged**", if nothing has changed.

But in both cases "**unchanged**" and "**authorized, changed**" the rules are up to date. Only in the case "**unauthorized, changed**" something goes wrong and ClearURLs tries to download by the next browser start and until the restart ClearURLs uses the old rules.

**Comment by grahamperrin** [comment]
Thanks, the addition of the wiki page resolves this issue.
