### ISSUE TITLE
Possible Bug with Facebook

### ISSUE THREAD

**Issue by EstherMoellman** [KevinRoebert/ClearUrls#19]
I tested 5 times ClearUrls with both, FF 56.0.2 and 57.0.2 (64-bit):

When scrolling down Facebook main page, at maximum speed, for more than 15 second... then the whole browser freezes (not 100%, but 90%). RAM and CPU go up. It seems like a kind of loop.

Facebook' tab also freezes, and bottom posts go in a kind of blank space in an endless upload (as you can see in the above attached gif image). 

I can't say if it is an incompatibility issue with other add-ons. But I did same test with similar add-ons (Neat URL and Pure URL), and Facebook worked perfectly, no bug, no freezes. 

[https://i.stack.imgur.com/hBbTY.gif](url)

**Comment by grahamperrin** [comment]
Not reproducible with Waterfox 56.0 and around a hundred other extensions enabled on FreeBSD-CURRENT. 

Your GIF: 

![hbbty](https://user-images.githubusercontent.com/192271/33806726-26500ae4-ddc4-11e7-837e-e89bdc223253.gif)

– that's normal when content is loading, not persistent. 

----

Side note: I use [Scrollmap](https://addons.mozilla.org/addon/scrollmap/), which can be quirky with sites such as Facebook … if the map disappears then I use a mouse wheel and keyboard to scroll and page down and up.

**Comment by EstherMoellman** [comment]
More info:

I did a clean FF portable install.
Zero add-ons. Just ClearUrls installed.
And... same bug happened.

Some times takes 15 seconds, other times 30s or 60s etc... it is a little bit randomized, but sooner or later the bug appears.
I repeat, this is happening when you scroll down the Facebook main page, pressing down the mouse/arrow all the time (without pausing), maximum speed... everything freezes, not completely, but almost completely. And it is not temporary. The only solution is to restart the browser.

This is happening only with ClearUrls installed.
Not installed, no bug.
With PureURL or NeatURL, the bug doesn't appear.

**Comment by KevinRoebert** [comment]
We will investigate.

**Comment by KevinRoebert** [comment]
Hi, we have investigated this. We're agree with @grahamperrin, it is only a normal loading process.
ClearURLs blocks in our tests only the **ref** field.

Some time ago we had a similar case in #11. The reason for the long loading times was, that the website was trying to load excessively the advertising scripts.

We think that this will be the reason for your long loading times.

As an attachment you will find an excerpt from the log:
![unbenannt](https://user-images.githubusercontent.com/28713602/34059953-cce51216-e1e1-11e7-8086-187bf7884850.PNG)

**Comment by EstherMoellman** [comment]
Hi,

In my case, I didn't see Facebook tab and FF browser recovering from being stuck/frozen.
I also didn't see it happening without ClearURL. It is only happening with ClearURL.

But even if it is a kind of "normal loading process", at least it is a strange one. Even if the stuck/frozen symptom is a temporary one or a short one... it is very strange. I never saw it in the past!

Anyway, thank you.
I don't blame at all the add-on.
I reported the bug because I like the add-on.
