### ISSUE TITLE
Some tracking links

### ISSUE THREAD

**Issue by grenzor** [KevinRoebert/ClearUrls#2]
Some links which can be cleaned

https://www.reddit.com/r/subreddit?ref=trending_sr_somenum 

https://www.reddit.com/r/subreddit/comments/random/title/random/?context=3&utm_content=context&utm_medium=user&utm_source=reddit&utm_name=frontpage

https://www.reddit.com/r/subreddit/comments/random/title/random/?sh=random&st=random

https://out.reddit.com/someRandomCharacters?url=https%3A%2F%2Factual.url.com

https://twitter.com/twitter?ref_src=twsrc^google|twcamp^serp|twgr^author
(when visiting twitter from google or search engines/affiliates)

https://twitter.com/search?q=term&src=tren

https://youtube.com/v=*&feature=youtu.be&a (feature tracks users who clicked the link. also 't' parameter may sometimes be there so might need to take care of that properly)

https://addons.mozilla.org/whatever/firefox/addon/someaddon/?src=hp-dl-mostpopular (addons site has a few of these but I heard they can't be cleared for security reasons. is this still true?)

**Comment by Atavic** [comment]
You should provide real reddit links for testing.  

`https://twitter.com/search?q=term&src=tren` can be stripped down to:
`https://twitter.com/search?q=term`

Youtube `t` parameter is for starting at a specific time in the video.

AMO `scr` parameter is mozilla tracking the previous page, similar to twitter.

**Comment by grenzor** [comment]
?? 

I know all that. t is for time that's why I said it needs to be taken care of properly so if the link is cleaned the t parameter is not accidentally removed in the process. src is Mozilla's tracking that's why I posted it here. But afaik it can't be cleaned due to security reasons (maybe the dev here might know a workaround so I posted it here).

**Comment by Atavic** [comment]
`https://addons.mozilla.org/en-US/firefox/addon/umatrix/` works fine, while
`https://addons.mozilla.org/en-US/firefox/addon/umatrix/?src=hp-dl-mostpopular` has the mozilla parameter, there are zero security reasons for that.

**Comment by grenzor** [comment]
Are you sure you're in the right repo? 

Again, of course you can manually remove the url to make it work. The whole point is a WebExtension like ClearUrl can't clear it due to security reasons: https://bugzilla.mozilla.org/show_bug.cgi?id=1310082

**Comment by KevinRoebert** [comment]
> https://www.reddit.com/r/subreddit/comments/random/title/random/?context=3&utm_content=context&utm_medium=user&utm_source=reddit&utm_name=frontpage

All utm fields are already globally blocked, so we do not need specific **utm** rules for reddit.

As Atavic said, it would be nice if you can provide real reddit links, so we can study the link and check if the **ref**, **context**, **sh** or **st** field are necessary for reddit.

> https://out.reddit.com/someRandomCharacters?url=https%3A%2F%2Factual.url.com

To implement this, we have to implement a new feature into the addon, this can take a while.

> Of course you can manually remove the parameter. The whole point is a WebExtension like ClearUrls can't clear it due to security reasons: https://bugzilla.mozilla.org/show_bug.cgi?id=1310082

It is not allowed to modify Mozilla links, so we can not implement this feature, but we want to implement a feature in which the user can add own rules, so this is a little sneaky workaround (in a future version of this addon)

> https://youtube.com/v=*&feature=youtu.be&a (feature tracks users who clicked the link. also 't' parameter may sometimes be there so might need to take care of that properly)

This field is already blocked.

> Youtube t parameter is for starting at a specific time in the video.

That is correct. So, we can not block the **t** field.

> https://twitter.com/search?q=term&src=tren can be stripped down to:
https://twitter.com/search?q=term

We add a new rule for the **src** field on twitter.

**Comment by KevinRoebert** [comment]
> > https://out.reddit.com/someRandomCharacters?url=https%3A%2F%2Factual.url.com

> To implement this, we have to add a new feature to the addon, this can take a while.

We implement this feature in the latest version of the add-on (v. 1.1.2.4) with the commit: [https://github.com/KevinRoebert/ClearUrls/commit/c256461340d4f04496e639e1245a8a872fbfbc42](url)

**Comment by grenzor** [comment]
The new ref addition doesn't clean this properly: https://twitter.com/twitter?ref_src=twsrc^google|twcamp^serp|twgr^author

**Comment by KevinRoebert** [comment]
We add a rule for this parameter.

**Comment by grenzor** [comment]
Now both https://twitter.com/search?q=term&src=tren and https://twitter.com/twitter?ref_src=twsrc^google|twcamp^serp|twgr^author will be cleaned properly?

**Comment by jingofett** [comment]
> Now both https://twitter.com/search?q=term&src=tren and [https://twitter.com/twitter?ref_src=twsrc^google|twcamp^serp|twgr^author](https://twitter.com/twitter?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor) will be cleaned properly?

I am also still having this issue. It seems that the cleaning is only done on tweet links from google, but pages that directly lead to  a profile are uncleaned.

https://twitter.com/CNN?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor - parameters not removed
https://twitter.com/CNN/status/1346523125857529858?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Etweet - parameters removed
https://twitter.com/search?q=cnn&ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Esearch - parameters not removed
