### ISSUE TITLE
Question regarding logging

### ISSUE THREAD

**Issue by crssi** [KevinRoebert/ClearUrls#20]
When logging is enabled, where I can find the logs?

**Comment by Atavic** [comment]
Console:  Developer submenu or press Ctrl+Shift+J (on M$).

**Comment by crssi** [comment]
@atavic, and then in the next moment you find out nothing is there? :)

**Comment by KevinRoebert** [comment]
Thank you for your question. I read also #18 and yeah it's true a description or instructions for using ClearURLs would be nice. So I will write here on GitHub into the Wiki some useful tips.

To answere quickly your question. We've set the link to the log in to the head on the labe "ClearURLs" next to the logo:

![clearurls_issue_20](https://user-images.githubusercontent.com/28713602/33844929-16b49a9e-dea2-11e7-85a2-ef700b56b3e3.png)
