### ISSUE TITLE
YouTube search suggestions not working

### ISSUE THREAD

**Issue by xyrolaith** [KevinRoebert/ClearUrls#22]
Using ClearUrls 1.2 on Firefox 57.0.2

The search suggestions on YouTube aren't working as one or more of the gs_ parameters are required.

Before processing:
> https://clients1.google.com/complete/search?client=youtube&hl=en&gl=de&sugexp=ytcle%2Cryff%3D1%2Crwff%3D0%2Cyrl%3D10%2Ccpf%3D1%2Ccfro%3D1%2Cccl%3D1%2Ccpf%3D1%2Cryff%3D1%2Crwff%3D0%2Cyrl%3D10&gs_rn=64&gs_ri=youtube&ds=yt&cp=7&gs_id=t&q=searchstring&callback=google.sbox.p50&gs_gbg=some_id

After processing:
> https://clients1.google.com/complete/search?client=youtube&hl=en&gl=de&sugexp=ytcle%2Cryff%3D1%2Crwff%3D0%2Cyrl%3D10%2Ccpf%3D1%2Ccfro%3D1%2Cccl%3D1%2Ccpf%3D1%2Cryff%3D1%2Crwff%3D0%2Cyrl%3D10&ds=yt&cp=7&q=searchstring&callback=google.sbox.p50&

Rule:
> gs_[a-zA-Z]*=[^\/|\?|&]*(\/|&(amp;)?)?

**Comment by KevinRoebert** [comment]
I hope the fix works :)

**Comment by xyrolaith** [comment]
Thanks a lot. The search suggestions are working now.
