### ISSUE TITLE
Few Facebook referer trackers 

### ISSUE THREAD

**Issue by Rtizer-9** [KevinRoebert/ClearUrls#24]
These are some parameters not removed when browsing facebook:
hc_ref, pnref, see_more_ref, ref, hc_ref, fref, timeline_context_item_type, timeline_context_item_source

**Comment by Atavic** [comment]
`timeline_context_item_type, timeline_context_item_source` indicate a link followed from your own FB timeline, nothing more. `see_more_ref` and other referrals seem internal to FB only.

As you're logged on FB, they appear innocuous to me.

**Comment by Rtizer-9** [comment]
I still think that such kind of things has possibility of being used in behavioural tracking. Facebook was accused and was caught when they conducted a psychological experiment on facebook users by excluding words from news feed pertaining to a certain emotion **WITHOUT** users' consent.

[https://www.forbes.com/sites/kashmirhill/2014/06/28/facebook-manipulated-689003-users-emotions-for-science/#4c7d9c13197c](url)
[https://www.theguardian.com/technology/2014/jul/02/facebook-apologises-psychological-experiments-on-users](url).

**Comment by Atavic** [comment]
Well sure. But you're logged into that social site and you're supposed to agree with being tracked. Can you prevent some tracking? Sure, but Facebook will try hard to make your social experience as bad as possible. I left FB, but I need to log into some forums that track you a lot, for these sites I use a dedicated browser.
