### ISSUE TITLE
search on google maps does not give you suggestions

### ISSUE THREAD

**Issue by crssi** [KevinRoebert/ClearUrls#27]
open maps.google.com and then start typing a place into search
normally it shows you expanded suggestions
if ClearUrls is enabled then this feature does not work

cheers

**Comment by crssi** [comment]
stripping and of the following parameters `gs_gbg, gs_l, gs_mss, gs_rn` will break the search on maps.google.com

cheers

**Comment by KevinRoebert** [comment]
Thanks for all the messages :)

We will develop exceptions for the Google Maps suggestions.

**Comment by crssi** [comment]
Hey, no problem. I am glad I can contribute, even if it is a small one.
Thank you for your work and fast response.

**Comment by Atavic** [comment]
Queries are sent to Maps JavaScript API.

**Comment by KevinRoebert** [comment]
I hope it works.

**Comment by crssi** [comment]
Tested and works.
You are a champ. :)

Cheers

**Comment by crssi** [comment]
Oh... should I close or would you like to close when appropriate?

**Comment by KevinRoebert** [comment]
You can close it :)
