### ISSUE TITLE
switching to a new log page doesn't scroll up

### ISSUE THREAD

**Issue by crssi** [KevinRoebert/ClearUrls#28]
reproduce steps:
open log
select "show 100 entries"
scroll to the bottom
select any other page

expected would be to start from top, but intead the page stays at bottom

**Comment by KevinRoebert** [comment]
Hi @crssi,

this is not a bug. In order for all new entries to be displayed, the log must be closed and reopened. The new log entries are only displayed when reopening, not even when reloading via F5.

**Comment by crssi** [comment]
I am not saying that this is a bug, but rather annoyance.
When you click the next index page, a natural expectation would be to start from top.
