### ISSUE TITLE
Gmail Attachments

### ISSUE THREAD

**Issue by sciguyryan** [KevinRoebert/ClearUrls#3]
Hi there!

This report is for Firefox nightly.

I noticed this morning that CleanURLs breaks the downloading of attachments from GMail. I checked to ensure that CleanURLs was the underlying issue by disabling it and attempting to download the same attachment.

After disabling the extension the attachment downloaded without an issue.

I'm not sure if there is anything you can do about this but I figured that I would let you know regardless!

**Comment by KevinRoebert** [comment]
We have add an exception for the google mail XHR requests on `mail.google.com/mail/u/0/`.
Now it should work. Please write a comment, if it has worked or not.

Thanks for reporting.

**Comment by sciguyryan** [comment]
Hi Kevin.

I can confirm that the fix works for adding attachments and downloading them.

Thanks for the super fast response!
