### ISSUE TITLE
Search on zillow.com [reported over addons.mozilla.com]

### ISSUE THREAD

**Issue by KevinRoebert** [KevinRoebert/ClearUrls#33]
An issue with the search on zillow.com, reported over the mozilla addon page.

> It seems to block the map on the left side of the property search result on zillow.com. This occurs when looking at a saved map search or a new map search.

**Comment by Atavic** [comment]
I did a search and by clicking on top-left Public View I got a map, created with 10 different tiles, as

`https://ecn.t3.tiles.virtualearth.net/tiles/r0320101110232313.png?g=6243&mkt=en-us&shading=hill&lbl=l1&stl=fb`

`https://ecn.t2.tiles.virtualearth.net/tiles/r0320101110232312.png?g=6243&mkt=en-us&shading=hill&lbl=l1&stl=fb`

**Comment by KevinRoebert** [comment]
ClearURLs actually blocked the request because there was a field called "**adtech**". I adjusted the "**adtech**" rule so that at the end there is a point.
