### ISSUE TITLE
Login with Google+ at a WordPress site

### ISSUE THREAD

**Issue by grahamperrin** [KevinRoebert/ClearUrls#35]
https://pikeralpha.wordpress.com/2018/02/15/a-new-start/ whenever I aimed to reply with ClearURLs 1.2.1.4 filtering enabled, a click on the _g+_ button caused something to occur but nothing visibly Google-related. 

With filtering disabled, after a reload of the page a click on the button leads to: 

> Connecting to Google+

– with an indeterminate progress bar (barber pole) … that seems to be endless, so I don't know whether there's something else at play here. 

![2018-02-24 09 44 28 waterfox](https://user-images.githubusercontent.com/192271/36634041-8bdb2ca0-1996-11e8-88f1-1242ab894573.png)

**Comment by KevinRoebert** [comment]
Hello, on the first try in my browser with quite a few other addons, it did not work either.

But if you only use a fresh installation of Firefox with ClearURLs then it will work through Google. I think it's due to one of the other addons.

Does the error occur even with only ClearURLs?

**Comment by grahamperrin** [comment]
>> …  I don't know whether there's something else at play here. … 

> … if you only use a fresh installation of Firefox with ClearURLs then it will work through Google. 

OK, yep. 

Not tested by me with Firefox, but with ClearURLs alone added to a new profile in Waterfox 56.0.4_4 on FreeBSD-CURRENT: 

- there's a **pop-up window** in response to a click on the _g+_ button. 

> I think it's due to one of the other addons.

Agreed. That, or I need to review pop-up related preferences. 

Apologies for the noise (and laziness)! Please label this as _invalid_

**Comment by grahamperrin** [comment]
> … on the first try in my browser with quite a few other addons, it did not work either. …

@KevinRoebert hi, a favour please. I'm struggling to understand what might be causing other issues in my case. Please, can you post your own `about:support` troubleshooting information to a paste bin? If not the whole caboodle, just a list of extensions. 

Many thanks. 

(Issues such as, advertisements blocked by … I don't know what …)

**Comment by grahamperrin** [comment]
AFAICT this was simply an issue with cookies:

- symptoms were complicated by tracking protection, and by _disabling_ things such as uBlock Origin (with uBlock Origin disabled, the load time was absurdly long)
- eventually worked around by making an allowance for `https://accounts.google.com`

– after I re-enabled uBlock Origin (and filtering by ClearUrls) it became much easier to identify the issue.
