### ISSUE TITLE
Rule incorrectly matching asyncRefreshAnalysis=1

### ISSUE THREAD

**Issue by moyerr** [KevinRoebert/ClearUrls#36]
ClearURLs is stripping `asyncRefreshAnalysis=1&asyncRefreshLocalMediaAgent=1&` based on the rule `[a-zA-Z_]*ref[a-zA-Z_]*=[^\/|\?|&]*(\/|&(amp;)?)?`

As far as I can tell, it's matching the `Ref` in the parameter names, but shouldn't this rule only match lowercase `ref`? This is breaking a website for me. Hoping for some insight as to why these parameters are getting caught by the regex.

**Comment by KevinRoebert** [comment]
Can anybody confirm the patch?

**Comment by moyerr** [comment]
@KevinRoebert I can confirm that the affected website now works! Thank you for this patch!
