### ISSUE TITLE
[SUGGESTION] Modifying Rules-Status checking 

### ISSUE THREAD

**Issue by mazesy** [KevinRoebert/ClearUrls#37]
Hi,

Running _ClearUrls_ 1.2.1.4 / Firefox 59.0.2 (x64) / Windows 7 (x64) flawlessly.

_ClearUrls_ checks the **_Rules-Status_** (calling 151.101.12.133) not once a week, not once a day or hour, but at each and every Firefox start.
- These rules aren't modified at a rhythm which requires a check on every start of the browser, last update of `data.json` took place 2 months ago... 
- The fact of being aware of connections established by the browser, hence by its extensions, on start seems to be, IMO, a valid caution, even when the connections are legitimate and healthy.

This is why I'd like to suggest an option that would let the user check manually and/or modify the automatic checking schedule.

Thanks.

**Comment by KevinRoebert** [comment]
That's a great suggestion. There will be an option for the manual update in an upcoming release of ClearURLs. We will adjust the settings of ClearURLs so that an automatic update will always be made at a certain interval.

Maybe the users have a suggestion, in which interval this should happen?

**Comment by mazesy** [comment]
Many thanks, @KevinRoebert -- Need to say I wasn't emphasizing on `data.json` not having been updated for 2 months (update is not an obsession) when the data as for now works perfectly well (I've tried other url cleaners and none performs as well, as fully as ClearUrls).

Looking forwards for _ClearUrls_' next step!

**Comment by KevinRoebert** [comment]
I've add your suggestion to the project tab and close this issue. Your suggestion is accepted :)

https://github.com/KevinRoebert/ClearUrls/projects/3#card-9606149

**Comment by mazesy** [comment]
I'm surprised no one emphasizes on this suggestion. A true pain IMO, so I'm really looking forwards to ClearUrls new version. Having this one and only connection (that of ClearUrls filters' list update availability checking) on each and every Firefox start is annoying.

**Comment by mazesy** [comment]
@KevinRoebert , many thanks, truly appreciated here. ClearUrls 1.2.2.8 installed/updated.

1- My concern was less ClearUrls checking be it for the rules' hash only or for the rules themselves than the systematic connection on the extension's start. I had in mind extensions such as HTTPS Everywhere which checks I think every 48 hours. Of course checking only the rules' hash is an improvement.

2- The new option for Stats on/off is much appreciated as well.

We may appear finicky but it's always and only with extensions/applications/software we are really fond of. The main, the most important was already achieved with previous versions of ClearUrls, which is cleaning up urls. But the extra, asked for and partially provided with the update is worth it IMO.

Nice work!
