### ISSUE TITLE
[SUGGESTION] Allow rule customization

### ISSUE THREAD

**Issue by hkclark** [KevinRoebert/ClearUrls#38]
Thank you for the helpful tool.  I was wanting to customize some of the definitions (for example, removing more from Amazon URLs -- such as `keywords=...` and hopefully also the `ref=...`, but I'm not sure yet if the syntax supports that on the "path" part of the URL).  What about having a way that users can specify their own data.json style rules and that gets merged with what is downloaded from github?  My initial thought was something like a `data.json` that users can drop in a specific directory under their firefox profile, but I'm guessing extensions can't read files from the local filesystem for security reasons.  So maybe entries under about:config instead?  (I was just trying to think of something simple that wouldn't require new UI elements or anything overly complicated to implement.)

**Comment by KevinRoebert** [comment]
Hi, mozilla extensions can't read from disk. They only can read from one dir. On windows and on my system the path is `C:\Users\Username\AppData\Roaming\Mozilla\Firefox\Profiles\mtf1wp6o.default\browser-extension-data\{74145f27-f039-47ce-a470-a662b129930a}`. But if you look at our project tab, you can see the following: https://github.com/KevinRoebert/ClearUrls/projects/3

If you replace the data under the path ahead, the file will be overwritten after a restart from firefox.

**Comment by hkclark** [comment]
OK, thanks.  Yes, several items on project tab could be extremely helpful.  Thank you
