### ISSUE TITLE
BUG: e10s + Facebook issue

### ISSUE THREAD

**Issue by vertigo220** [KevinRoebert/ClearUrls#39]
### Prerequisites
* [yes] Can you reproduce the problem in a **fresh** firefox profile with **only** ClearURLs?
* [yes] Are you running the latest version of ClearURLs?
* [yes & no (see below)] Are you have changed settings under `about:config`?

### Description

When running Firefox or Waterfox in multi-process (e10s) mode, when ClearURLs is active (filters enabled), it causes the entire browser to break when using Facebook. I first noticed it in Waterfox 56.1.0 x64 and spent hours narrowing it down to this addon and then checking different variations to see when it happens and when it doesn't. It's definitely ClearURLs, which I've further verified by the fact the same thing happens with a fresh Firefox 59.0.3 x64 install with only this addon installed. And the problem happens regardless of the logging and badges settings; it's only related to whether it's filtering or not. I'm not sure what exactly triggers it, or if other sites are affected, though I tried with Amazon fairly extensively and with some other sites a bit. Facebook works fairly regularly, though not consistently.

What happens is that everything will be fine, then all of a sudden clicking on the icon for any addon in the navigation toolbar or the status/addon bar (in Waterfox with Classic Theme Restorer addon) will result in it only showing a sliver of that addon's pop-up, and the rest doesn't show. The items in the bookmarks bar don't seem to be affected. The other thing that happens is that the entire browser stops loading web pages. All tabs are affected. In fact, when it first started happening I was testing something out which required copy/pasting into Facebook chat and reloading the page, and when it kept breaking I thought for a while it was my crappy internet, until I finally tried another browser. The only way to get everything working again is by restarting the browser or _possibly_ by waiting a while (several minutes or more), since I _think_ that's what I did when it happened at first and I thought it was the internet dropping out.

### Steps to Reproduce

1. Install ClearURLs and enable filtering
2. Log in to Facebook
3. The thing that seems to trigger it the most consistently is opening a chat with someone and typing or pasting something into it, then refreshing the page. It's too inconsistent for me to be able to figure out more than this, i.e. I'm not sure if typing something then deleting it before refreshing has more or less of a chance of causing it, or if it's even necessary to type anything. And in fact, when I first tested it in Firefox after doing most of the testing in Waterfox, Firefox seemed to break easier/more consistently, but it still seemed to require a page reload. After refreshing Firefox (to wipe the slate), all it took was to load Facebook and it would instantly break. So I would restart Firefox, and when it reopened it would automatically reload Facebook and it would break right away again. Disabling ClearURLs stopped this. Disabling multiprocess in Waterfox stops it as well.

**Expected behavior:** [What you expected to happen]

Should be obvious, but using ClearURLs shouldn't break the browser when using Facebook and e10s.

**Actual behavior:** [What actually happened]

See above

### System
* **Version**: 1.2.1.4
* **Platform**: Win10x64

### Log
Nothing was logged in Firefox. I will try to get a log from Waterfox.

**Comment by vertigo220** [comment]
Just tried to get a log in Waterfox. Waited several minutes to let the issue fix itself vs restarting the browser (which did work), but still no Facebook entries in the log, which makes sense, since I'm not clicking any links, just refreshing the page.

**Comment by KevinRoebert** [comment]
Unfortunately, I did not succeed in reproducing this bug. Is anyone able to reproduce this bug?

**Comment by vertigo220** [comment]
It could take a while. As I said, sometimes it happens immediately, other time it takes several minutes. I do hope you or someone else can reproduce it, since this has been probably the most annoying issue I've dealt with lately, and not only would I like to get it working for my sake, but also to avoid someone else having to deal with it.

**Comment by KevinRoebert** [comment]
It will be fixed, 

But we moved to gitlab. Your issue report is now on gitlab: https://gitlab.com/KevinRoebert/ClearUrls/issues/39

**Comment by vertigo220** [comment]
Ah, thanks. I was worried it was being dropped since you couldn't reproduce it. I'll subscribe to it over there, let me know if you need me to test anything.

Is the move due to MS buying github, by chance?

**Comment by KevinRoebert** [comment]
> Is the move due to MS buying github, by chance?

Yes :)
