### ISSUE TITLE
Breaks some Amazon functionality

### ISSUE THREAD

**Issue by vertigo220** [KevinRoebert/ClearUrls#41]
### Prerequisites
* [Yes] Can you reproduce the problem in a **fresh** firefox profile with **only** ClearURLs?
* [Yes] Are you running the latest version of ClearURLs?
* [Yes & No] Are you have changed settings under `about:config`?

### Description

For items with a size selection (e.g. https://www.amazon.com/Bionic-DVML-Driving-Gloves-Black/dp/B001ZTRDCI/ref=sr_1_2?keywords=bionic%2Bdriving%2Bgloves&th=1&psc=1), you can't select size. When trying, most of the item description and images and links to other products are all grayed out and the page becomes less responsive (basically it's as if it's stuck in the middle of the change); products with a row of multiple choices where you click the box you want (products with different lenghts, colors, etc) seem to work, so there appears to be something different with the single drop-down selection method for clothing sizes; the above site did work a couple times with ClearURLs enabled, but it failed to work a few dozen times, and it was very consistent about not working and working when ClearURLs was filtering and not filtering, respectively. This is in both Watefox 56.1.0 x64 and Firefox 59.0.3 x64, with Firefox on a clean profile.

### Steps to Reproduce

1. Go to above site
2. Change the size (it might take a few tries, but it typically happens pretty quickly)
3. Go to an item with multiple length/color/diameter/etc choices (good options are string, rope, heat shrink, cables, etc) where the different choices are chosen by selecting different boxes instead of different options within a single drop-down. These product pages are unaffected.

**Expected behavior:** [What you expected to happen]

The page should function normally.

**Actual behavior:** [What actually happened]

The page breaks, becoming more or less frozen (though not locked up).

### System
* **Version**: 1.2.1.4
* **Platform**: Win10x64

### Log

Nothing was logged

**Comment by KevinRoebert** [comment]
I hope the fix works. Can anybody confirm the fix?

**Comment by vertigo220** [comment]
Where do I put that file?

**Comment by KevinRoebert** [comment]
You've to restart firefox. Than ClearURLs download automatically the new rule file.

**Comment by vertigo220** [comment]
Thanks! I can't speak to the other issues, but the Amazon one is fixed!
