### ISSUE TITLE
Feature request/suggestion

### ISSUE THREAD

**Issue by vertigo220** [KevinRoebert/ClearUrls#42]
Color the icon to reflect whether filters are enabled (green) or disabled (orange or red) and possibly add an option to replace badges with a different color (e.g. yellow) when active or use a different icon completely (e.g. can with lid open).

**Comment by KevinRoebert** [comment]
First of all, thanks for your suggestion. We will consider whether to include this proposal. However, these are UI proposals. We will first work on our two projects (https://github.com/KevinRoebert/ClearUrls/projects/4, https://github.com/KevinRoebert/ClearUrls/projects/3) before we can deal with their proposal.

Is there any interest in this feature/suggestion #42 from other users?

**Comment by vertigo220** [comment]
This can easily be a low-priority item, so no worries. I'd rather you focus on the core functionality first. 😃

**Comment by KevinRoebert** [comment]
Added in version 1.2.2.8.
