### ISSUE TITLE
[SUGGESTION] Statistics removed or as an option

### ISSUE THREAD

**Issue by mazesy** [KevinRoebert/ClearUrls#44]
I don't understand the pertinence of the _Statistics_ feature. It doesn't bring anything, knowing that x% of elements have been blocked is a non-information IMO, and meanwhile it writes to disk again and again.

I'd suggest removing this non-feature or setting it as a toggle option under Features - Logging - Badges.

Who reads the stats? What does it bring, an element of satisfaction? Nonsense IMO.

Otherwise, _ClearUrls_ does a swell job : powerful, efficient.

**Comment by elypter** [comment]
i like seeing what an addon does. especially if you use multiple privacy addons it can give you a measure of how well they work together. it wouldnt harm though to have it as an option. even if only 2 numbers are being recorded(i hope that is the case) it can tell how active the user is. this information is obtainable in many other ways as well so i see it as a minor privacy risk but its not completely 0.

**Comment by mazesy** [comment]
The point is the stats here bring a quantity and a ratio but no details, which is why I don't perceive its true pertinence. I run several privacy extensions as well and I do refer to the detail of what has been blocked because information is provided, not only numbers. As well with Stylus and ViolentMonkey for which I do enable the badges because their is more info behind. But just knowing the number of blocked elements is for me the same as knowing there are 2 or a hundred ghosts in a haunted house : who are they?!

**Comment by KevinRoebert** [comment]
> even if only 2 numbers are being recorded(i hope that is the case)

Yes this is the case :)

> The point is the stats here bring a quantity and a ratio but no details, which is why I don't perceive its true pertinence.

Sure, but you can enable the logging function to see the details. But you're right, the statistic function is rather a little gimmick and should only serve as an idiom to see if the addon works at all and how much it worked.

> and meanwhile it writes to disk again and again.

This is known to us with the many write accesses. That's why we started the project "Memory Management".

In one of the next versions I will insert the statistic function as an optional feature that can be turned on and off. It will be on by default.

**Comment by KevinRoebert** [comment]
Added in version 1.2.2.8.

**Comment by 6-AND-9** [comment]
Statistics are great if you want to have an overview of just how much of URLs is garbage on average. Even research studies can be designed and executed off this. So I don't think it is 'nonsense', even though OP feels that way.
