### ISSUE TITLE
Possibly misleading formulation in wiki page 1.1

### ISSUE THREAD

**Issue by elypter** [KevinRoebert/ClearUrls#46]
> The Badges switch activates the badge functionality (See WebExtensions API) of the addon. In the current version (1.2.x.x) the addon counts the blocked elements per url.

shouldn't the last word "url" rather be "tab"?

**Comment by KevinRoebert** [comment]
I've change it to:
https://github.com/KevinRoebert/ClearUrls/wiki/1.1-Interface/150c588b924088571a2a42e0fb85f07d45d3a9f2

**Comment by elypter** [comment]
nice. that makes it clear.
