### ISSUE TITLE
[suggestion]Please increase the default items per page in the log

### ISSUE THREAD

**Issue by elypter** [KevinRoebert/ClearUrls#47]
currently it is 5 which is a little low. it should be one of the selectable numbers. 10 fit on most screens without scrolling. if you want to keep 5 then it should be in the drop down menu so you can switch back and forth.

**Comment by KevinRoebert** [comment]
https://github.com/KevinRoebert/ClearUrls/commit/ff88d9c0ae14320a388441d78cd68cf3a4980782

**Comment by KevinRoebert** [comment]
Added in version 1.2.2.8.
