### ISSUE TITLE
Breaks Fanatical link

### ISSUE THREAD

**Issue by vertigo220** [KevinRoebert/ClearUrls#48]
### Prerequisites
* [x] Can you reproduce the problem in a **fresh** firefox profile with **only** ClearURLs? - immediately after refreshing Firefox and installing ClearURLs, the page worked, but then a couple minutes later I tried again and it was broken until disabling filtering
* [x] Are you running the latest version of ClearURLs?
* [x] Are you have changed settings under `about:config`? - yes, in Waterfox, but not in Firefox

### Description

Going to this [link](https://fanatical.us1.list-manage.com/track/click?u=8c91a39196d452fc8446b9e62&id=249587180f&e=af5108abd3) with ClearURLs filtering enabled, the page doesn't load properly. Disabling filtering allows it to load. Disabling other addons doesn't have any effect, have similar results in Firefox with clean profile (see above). This is in Waterfox 56.2.0 x64, but since it happens in Firefox too that doesn't seem to matter.

### Steps to Reproduce

1. Enable filtering
2. Click the link
3. Disable filtering
4. Refresh the page

**Expected behavior:** [What you expected to happen]

The page should load properly with ClearURLs active. Also, it might be helpful to have some sort of whitelisting feature.

**Actual behavior:** [What actually happened]

The page doesn't load properly unless ClearURLs is disabled.

### System
* **Version**: 1.2.1.4
* **Platform**: Win10x64 Pro

### Log

| Before processing | After processing | Rule | Time |
|-------------------|------------------|------|------|
|https://fanatical.cdn.prismic.io/api/v2/documents/search?page=1&pageSize=1&lang=*&ref=Wv7hTCAAAGRi9xhk&q=%5B%5Bat(my.blog_template_groups.uid%2C%20%22win-one-of-ten-top-steam-pc-games%22)%5D%5D | https://fanatical.cdn.prismic.io/api/v2/documents/search?page=1&pageSize=1&lang=*&q=%5B%5Bat(my.blog_template_groups.uid%2C%20%22win-one-of-ten-top-steam-pc-games%22)%5D%5D | [\?\|&]ref[\_]?=[^\/\|\?\|&]* | 5/19/2018, 3:51:50 PM|

**Comment by KevinRoebert** [comment]
Latest Tuesday, the fix will be online.

**Comment by KevinRoebert** [comment]
Can anybody confirm the fix?

**Comment by vertigo220** [comment]
Works for me
