### ISSUE TITLE
Your addon brokes Google reverse image search

### ISSUE THREAD

**Issue by mooms06** [KevinRoebert/ClearUrls#5]
Hi,

If I search an image on Google with [Reverse Image Search](https://addons.mozilla.org/fr/firefox/addon/image-reverse-search/) and with ClearUrls activated, this will not works (open a new tab with the same image).
It works if I deactivate ClearUrls.
Firefox 55.0.3 x64 on Win7 x64.

Regards.

**Comment by toshiya44** [comment]
In other words, URLs like `https://www.google.com/searchbyimage?image_url=` needs to be whitelisted/exempted from cleaning, because in this case the parameter is being used for a legitimate purpose.

**Comment by KevinRoebert** [comment]
I hope the new commit fix the issue.

**Comment by toshiya44** [comment]
It works. Thank you.

**Comment by pepablock** [comment]
I installed this add-on today and came across the same issue. For example, when I google dog pictures and click on the picture, then copy the link and paste it into the address bar it will strip some parameters in the link and therefor not showing the exact picture.
For eg.:
`https://www.google.com/search?q=dog&newwindow=1&tbm=isch&sa=X&#imgrc=uRwQu3JNq09xpM:`
become
`https://www.google.com/search?q=dog&newwindow=1&tbm=isch&sa=X&#`

**Comment by KevinRoebert** [comment]
I hope the fix works.

 

Von: 4anon [mailto:notifications@github.com] 
Gesendet: Sonntag, 5. November 2017 20:24
An: KevinRoebert/ClearUrls <ClearUrls@noreply.github.com>
Cc: Kevin Röbert <6roebert@informatik.uni-hamburg.de>; Assign <assign@noreply.github.com>
Betreff: Re: [KevinRoebert/ClearUrls] Your addon brokes Google reverse image search (#5)

 

I installed this add-on today and came across the same issue. For example, when I google dog pictures and click on the picture, then copy the link and paste it into the address bar it will strip some parameters in the link and therefor not showing the exact picture.
For eg.:
https://www.google.com/search?q=dog <https://www.google.com/search?q=dog&newwindow=1&tbm=isch&sa=X&#imgrc=uRwQu3JNq09xpM> &newwindow=1&tbm=isch&sa=X&#imgrc=uRwQu3JNq09xpM:
become
https://www.google.com/search?q=dog <https://www.google.com/search?q=dog&newwindow=1&tbm=isch&sa=X&#> &newwindow=1&tbm=isch&sa=X&#
