### ISSUE TITLE
?ftag=

### ISSUE THREAD

**Issue by grahamperrin** [KevinRoebert/ClearUrls#51]
In response to a notification (from `https://www.cnet.com`, I guess, where I allow notifications), I found myself at: 

- https://www.cnet.com/news/turns-out-pluto-might-really-be-a-giant-comet/?ftag=CAD-03-10aaj8j

## Enhancement request

Please, would it be possible/appropriate to apply filters for things such as `?ftag=CAD-03-10aaj8j` to be cleared? 

https://www.cnet.com/news/turns-out-pluto-might-really-be-a-giant-comet/ appears fine, as far as I can tell. 

## Environment

Waterfox 56.2.0 on FreeBSD-CURRENT, 

```text
$ pkg info waterfox | grep Version
Version        : 56.2.0.13_4
$ date ; uname -v
Thu 24 May 2018 18:38:57 BST
FreeBSD 12.0-CURRENT #2 r333587: Mon May 14 01:59:02 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

ClearURLs 1.2.2.8

**Comment by KevinRoebert** [comment]
Added.
