### ISSUE TITLE
Breaks Amazon Q&A search functionality

### ISSUE THREAD

**Issue by vertigo220** [KevinRoebert/ClearUrls#54]
I know support has moved to GitLab, but I've not been able to register there, and their "support" was useless. So I'm stuck here for now. As much as I share the concern over MS acquiring GitHub, GitLab so far is not impressing me. ☹️

### Prerequisites

* [x] Can you reproduce the problem in a **fresh** firefox profile with **only** ClearURLs?
* [x] Are you running the latest version of ClearURLs?
* [x] Are you have changed settings under `about:config`?  (NO)

### Description

Amazon Q&A doesn't work. Typing a search term results in the message "Sorry, we were unable to perform your search at this time. Submit your question to our community by clicking the 'Ask' button." Disabling ClearURLs allows the Q&A search to work properly.

### Steps to Reproduce

1. Make sure filtering is enabled.
2. Go to a product page on Amazon and type in the Q&A search box (don't hit enter).
3. You should get the above error. If not, delete what you've typed, wait a few seconds, then try again.
4. Disable filtering.
5. Retry typing in the search box. It should work now. If not, delete what you've typed, wait a few seconds, then try again.

**Expected behavior:** [What you expected to happen]

The search function should work with filtering enabled.

**Actual behavior:** [What actually happened]

It doesn't.

### System
* **Version**: 1.2.2.16 (also did it on 1.2.2.15)
* **Platform**: W10x64

### Log

| Before processing | After processing | Rule | Time |
|-------------------|------------------|------|------|
|https://www.amazon.com/ask/livesearch/search?query=test&asin=B077ZGRY9V&forumId=&liveSearchSessionId=375785d6-3643-c826-b560-f958e3234f55&liveSearchPageLoadId=f56944c1-7f45-e018-6a8a-f2a26cdf13ca&searchSource=LIVE_SEARCH_SOURCE&language=en_US	https://www.amazon.com/ask/livesearch/search?query=test&asin=B077ZGRY9V&forumId=&liveSearchSessionId=375785d6-3643-c826-b560-f958e3234f55& | liveSearchPageLosearchSource=LIVE_SEARCH_SOURCE&language=en_US | adId=[^\/\|\?\|&]*(\/\|&(amp;)?)? | 6/9/2018, 4:49:18 AM

**Comment by KevinRoebert** [comment]
https://gitlab.com/KevinRoebert/ClearUrls/issues/57

**Comment by vertigo220** [comment]
Updated to the latest version but still not working for me. I'm sure you noticed, but I just saw I put the break at the wrong place between the before and after columns.

**Comment by KevinRoebert** [comment]
Do you read the https://github.com/KevinRoebert/ClearUrls/blob/master/README.md#important-notice section?

**Comment by KevinRoebert** [comment]
You‘ve to change your Settings to gitlab

**Comment by vertigo220** [comment]
Strange. It was pointed to GitLab (I'd checked that shortly after the move), but must've reverted back after installing the new version. After changing it back to GitLab the problem appears to be fixed.
