### ISSUE TITLE
ClearURLs 1.1.2.4 versus Google authentication for various non-Google services: error 400, invalid_request, missing required parameter: client_id

### ISSUE THREAD

**Issue by grahamperrin** [KevinRoebert/ClearUrls#6]
## Steps

1. have a not logged in (NLI) view of, for example, <https://apple.stackexchange.com/>
2. enable ClearURLs filters
3. aim to log in, e.g. <https://apple.stackexchange.com/users/login?ssrc=head&returnurl=https%3a%2f%2fapple.stackexchange.com%2f>
4. click the _G+_ Google button

## Expected

- continuation of the authentication routine

## Actual result

> **400.** That’s an error.
> 
> **Error: invalid_request**
> 
> Missing required parameter: client_id
> 
> … 

## Workaround

- disable ClearURL filters
- revisit <https://apple.stackexchange.com/> and follow the log in routine successfully with Google. 

## Other examples

If I recall correctly, services such as GitLab are similarly affected.

**Comment by KevinRoebert** [comment]
I hope the new commit fix the issue.

**Comment by grahamperrin** [comment]
Sorry, I can not yet confirm the fix. 

This morning, Google authentication failed when I aimed to make the comment at https://gitlab.com/mjanetmars/switch-container/issues/9#note_43402948

I'd like to add more detail but (sorry) right now I'm heavily focused on umpteen other issues, unrelated to ClearURLs `:-)` … in the meantime, I can probably say that this morning's failure did **not** involve error 400.

**Comment by grahamperrin** [comment]
Not reproducible at this time. 

With ClearURLs filters enabled, I now get a saner response, for example: 

> https://gitlab.com/users/auth/google_oauth2/omniauth_error?error=Email+has+already+been+taken

> **422**
> The change you requested was rejected.
> 
> Make sure you have access to the thing you tried to change.
> 
> Please contact your GitLab administrator if you think this is a mistake.

– that's sane enough because (within the URL) _Email has already been taken_, which is probably true because when I could not authenticate with Google I authenticated with GitHub, and I do use the same e-mail address for both services. 

Hmm, although it's still version 1.1.2.4 here (released 2017-09-18) so I reckon that something other than ClearURLs was contributory to earlier problems! Apologies for the noise.
