### ISSUE TITLE
Google Translate broken

### ISSUE THREAD

**Issue by zanot** [KevinRoebert/ClearUrls#7]
Hello,

It seems that your add-on breaks [Google Translate](https://translate.google.com/).

Try a simple translation like "[hello](https://translate.google.com/#en/fr/hello)" with your add-on enabled, and we get a "Translation Error" as result.
![_a](https://user-images.githubusercontent.com/4114656/31492409-59f25fea-af3a-11e7-8c95-2de57bf02920.png)

When I disable the option "Filters", the translation is correctly done.
![a](https://user-images.githubusercontent.com/4114656/31492420-669198f6-af3a-11e7-9832-6d5c650c486b.png)

**Comment by KevinRoebert** [comment]
I hope everything is fixed. 
@zanto Thx for reporting the issue :)

**Comment by zanot** [comment]
GTranslate works perfectly, thank you.

But it seems,since I am trying your add-on that some websites, like Facebook, are very slow now... I will maybe do a report later.
